wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.33.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1696833301.646829
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      3:
      - 23
      4: 3.11.0
      5: 0.15.12
      6: 4.33.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
